### ISSUE TITLE
tests unassigned characters

### ISSUE THREAD

**Issue by ashinn** [feeley/r7rs-unicode-check#1]
Thanks for putting this together, it's useful to have something to compare against!

The loop in dump-unicode.scm outputs every code point, and it seems the assumption is that unassigned code points have neither any properties nor case mappings.  Running this on a newer version of Unicode (13) then reports errors such as

```
#x08be char-alphabetic? should return #f but returned #t
#x08bf char-alphabetic? should return #f but returned #t
...
```

when these are simply new code points added to the standard.  The dump should omit any code points which are unassigned at time of generation.

**Comment by feeley** [comment]
Thanks for reminding me that the test results were for Unicode 12.0.  I have updated them for Unicode 13.0.  What is the easiest way to tell if a code point is unassigned in a given version of the standard? I could add that information in the "expected-results.txt" file.

**Comment by ashinn** [comment]
I think UnicodeData.txt covers everything but unihan.  For that, Unihan_Readings.txt looks like the best canonical list.

I think the behavior on unassigned points should be implementation defined, to allow best effort at forwards compatibility.  Chibi assumes unassigned points have the same properties as the enclosing block, which is both statistically likely to be true and allows more efficient table representations.

**Comment by ashinn** [comment]
OK, now the only failed case for Chibi is:

`#x00df char-upcase should return #x00df but returned #x1e9e`

I'm not going to "fix" this because char-upcase is silly in a Unicode context.
`string-upcase` does the right thing.  Allowing `(char-downcase #\x1e9e) => #\xdf`,
but not reciprocating `(char-upcase #\xdf) => #\x1e9e` is a meaningless special
case that complicates both the implementation and use of the procedure.

Apart from that, this looks like a useful test suite now validated by both Gambit and Chibi.

**Comment by feeley** [comment]
Note that Gambit derives its character property tables by parsing the Unicode database files (using a rather large macro).  This is the file containing a 1KLOC macro: https://github.com/gambit/gambit/blob/master/lib/gambit/char/char%23.scm

Note that it contains this special case for `#\xdf` which is commented out:

```
    ;; add any deviations from the Unicode spec here

    (define substitutions
      '(
        ;;(#x00df . #("00DF" "LATIN SMALL LETTER SHARP S" "Ll" "0" "L" "" "" "" "" "N" "" "" "1E9E" ""))
        ))
```

so it is easy to get the Chibi character properties if desired.

**Comment by ashinn** [comment]
Yes, Chibi also reads from the Unicode database files (and even similar looking code, though not a macro but an offline code generator for various reasons).

I did consider just adding that one special case for `#\xdf` but decided against it :)
